# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a0685559fda3ccbb37b25b7a71eab4bf"
name = "Ebay Sync"
handle = "ebay-sync-6"
application_url = "https://footwear-woman-origins-ship.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "iacdevtest.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_inventory, read_inventory, read_products"

[auth]
redirect_urls = [
  "https://footwear-woman-origins-ship.trycloudflare.com/auth/callback",
  "https://footwear-woman-origins-ship.trycloudflare.com/auth/shopify/callback",
  "https://footwear-woman-origins-ship.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
